### ISSUE TITLE
How to compare and see changes between revisions?

### ISSUE THREAD

**Issue by inetpro** [octoquad/trello-snapshot#1]
I like the approach with the use of git for version control. Only question now remains how to compare and see changes between revisions. With Trello's .json file all in one line it becomes difficult to see only the changes.

```
$ git diff HEAD^ HEAD --color-words
```

**Comment by octoquad** [comment]
I think having the option to prettify / unminify the source JSON before storing it in Git might be a good idea. Added to 0.2 :)
